# Generated by Django 4.2.18 on 2025-02-18 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskDetails',
            new_name='TaskDetail',
        ),
    ]
