# Generated by Django 4.2.7 on 2025-03-05 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
